{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "Success" },
    { "expr": "rate(auth_failure_total[1m])", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 0 },
   "targets": [
    { "expr": "rate(http_total[1m])", "legendFormat": "TOTAL" },
    { "expr": "rate(http_get_total[1m])", "legendFormat": "GET" },
    { "expr": "rate(http_post_total[1m])", "legendFormat": "POST" },
    { "expr": "rate(http_delete_total[1m])", "legendFormat": "DELETE" },
    { "expr": "rate(http_put_total[1m])", "legendFormat": "PUT" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(latency_server_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(pizza_sold_total[1m])", "legendFormat": "Pizza purchases" },
    { "expr": "rate(pizza_fail_total[1m])", "legendFormat": "Purchase failures" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(pizza_earn_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "rate(latency_pizza_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}